In [2]:
import pandas as pd
import os
from src.__special__ import indices_path
import numpy as np

file_path = os.path.join(indices_path, 'INDEXP.csv')

INDEXP = pd.read_csv(file_path)

In [3]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

# Seleccionar todas las columnas menos la primera
INDEXP_pca = INDEXP.iloc[:, 1:].dropna()  # Esto selecciona todas las columnas excepto la primera y elimina NaN

# Estandarizar datos (equivalente a matriz de correlación en PCA)
scaler = StandardScaler()
data_scaled = scaler.fit_transform(INDEXP_pca)

# Aplicar PCA
pca = PCA(n_components=5)
pca_result = pca.fit_transform(data_scaled)

# Convertir resultados en DataFrame
pca_df = pd.DataFrame(pca_result, index=INDEXP_pca.index, columns=[f'PC{i+1}' for i in range(5)])

In [4]:
# 6. Ver la varianza explicada por cada componente
explained_variance = pca.explained_variance_ratio_

# 7. Cargas factoriales (coeficientes de los componentes principales)
loadings = pd.DataFrame(pca.components_, columns=INDEXP_pca.columns, index=[f'PC{i+1}' for i in range(5)]).T

# Mostrar las cargas factoriales
loadings


PC1       PC2       PC3       PC4       PC5
@dlog(exp1,0,12)       0.120798  0.261696  0.175128 -0.271865 -0.251008
@dlog(exp2,0,12)       0.188353  0.018110 -0.163118  0.112744 -0.054293
@dlog(exp3,0,12)       0.174244  0.156857 -0.213879 -0.024490 -0.064256
@dlog(exp4,0,12)       0.179010  0.125594 -0.210183 -0.062828 -0.061677
@dlog(exp5,0,12)       0.142445  0.174117 -0.034352 -0.280597  0.481417
@dlog(exp6,0,12)       0.181704  0.104289 -0.196224 -0.040104 -0.036218
@dlog(exp7,0,12)       0.159469  0.205319 -0.241102 -0.000966 -0.049819
@dlog(exp8,0,12)       0.169866  0.169373 -0.233973 -0.015436 -0.057274
@dlog(exp9,0,12)       0.173799  0.153355 -0.227905 -0.012528 -0.048951
@dlog(exp10,0,12)      0.181205  0.155679  0.009060 -0.192434 -0.092913
@dlog(exp11,0,12)      0.094772  0.311365  0.145481 -0.285499 -0.023166
@dlog(exp12,0,12)      0.131664  0.267259  0.168251 -0.232707 -0.100235
@dlog(exp1(-1),0,12)   0.145586  0.162451  0.207874  0.252051 -0.160575
@dlog(exp2(-1),0,12)   0.182495 -0.171395 -0.043577 -0.031213 -0.073332
@dlog(exp3(-1),0,12)   0.192873 -0.050462 -0.096754  0.200539 -0.009983
@dlog(exp4(-1),0,12)   0.193429 -0.063396 -0.104565  0.151624 -0.020131
@dlog(exp5(-1),0,12)   0.164168  0.079467  0.005677 -0.031476  0.521612
@dlog(exp6(-1),0,12)   0.191427 -0.084605 -0.088514  0.109336 -0.008216
@dlog(exp7(-1),0,12)   0.186234 -0.022552 -0.106614  0.277754  0.041378
@dlog(exp8(-1),0,12)   0.190964 -0.047322 -0.108612  0.224511  0.008519
@dlog(exp9(-1),0,12)   0.192281 -0.057712 -0.106699  0.195988  0.007659
@dlog(exp10(-1),0,12)  0.195965  0.038535  0.073338  0.005814 -0.068930
@dlog(exp11(-1),0,12)  0.127370  0.194931  0.201604  0.319321  0.112124
@dlog(exp12(-1),0,12)  0.157092  0.163657  0.226517  0.137414 -0.033936
@dlog(exp1(-2),0,12)   0.144718 -0.010925  0.324786  0.139186 -0.162064
@dlog(exp2(-2),0,12)   0.146170 -0.235451  0.001514 -0.280863 -0.155919
@dlog(exp3(-2),0,12)   0.169830 -0.236022  0.033044 -0.110483 -0.034963
@dlog(exp4(-2),0,12)   0.170035 -0.235402  0.018343 -0.134910 -0.045010
@dlog(exp5(-2),0,12)   0.159446 -0.077959  0.108227 -0.068895  0.509781
@dlog(exp6(-2),0,12)   0.165005 -0.237822  0.022844 -0.165332 -0.038686
@dlog(exp7(-2),0,12)   0.165769 -0.236292  0.046404 -0.071104  0.028534
@dlog(exp8(-2),0,12)   0.168141 -0.242537  0.031412 -0.105025 -0.014653
@dlog(exp9(-2),0,12)   0.168749 -0.241054  0.023122 -0.124266 -0.018206
@dlog(exp10(-2),0,12)  0.181919 -0.110584  0.170102 -0.084924 -0.088758
@dlog(exp11(-2),0,12)  0.129582 -0.000188  0.347777  0.161901  0.128940
@dlog(exp12(-2),0,12)  0.153669 -0.013633  0.347687  0.046911 -0.021778

In [5]:
# 8. Guardar resultados
pca_df.to_excel("PCA_Result.xlsx", sheet_name="PCA")

# 9. Mostrar resultados
explained_variance

array([0.66880315, 0.13342479, 0.07517508, 0.03002344, 0.02588353])

In [6]:
fact_load = loadings.to_numpy()

fact_load

array([[ 1.20797534e-01,  2.61695834e-01,  1.75127618e-01,
        -2.71865419e-01, -2.51007691e-01],
       [ 1.88353376e-01,  1.81101179e-02, -1.63117790e-01,
         1.12744201e-01, -5.42929067e-02],
       [ 1.74244095e-01,  1.56856686e-01, -2.13879264e-01,
        -2.44901417e-02, -6.42558658e-02],
       [ 1.79010049e-01,  1.25593899e-01, -2.10182675e-01,
        -6.28275327e-02, -6.16765603e-02],
       [ 1.42444978e-01,  1.74117478e-01, -3.43515918e-02,
        -2.80596606e-01,  4.81416970e-01],
       [ 1.81703720e-01,  1.04288601e-01, -1.96223744e-01,
        -4.01040610e-02, -3.62180234e-02],
       [ 1.59469006e-01,  2.05319344e-01, -2.41102386e-01,
        -9.66388025e-04, -4.98192135e-02],
       [ 1.69866499e-01,  1.69373398e-01, -2.33973319e-01,
        -1.54363788e-02, -5.72737072e-02],
       [ 1.73798826e-01,  1.53354588e-01, -2.27904718e-01,
        -1.25278424e-02, -4.89508738e-02],
       [ 1.81204796e-01,  1.55678797e-01,  9.05968210e-03,
        -1.92433507e-01

In [7]:
original_values = pd.read_csv(os.path.join(os.path.dirname(indices_path), "variables_originales_exp.csv"))

original_values

_date_         exp1  exp2  exp3      exp4       exp5     exp6  exp7  \
0    1995-01-01  5065287.362   NaN   NaN  2962.878  18261.007  30299.0   NaN   
1    1995-02-01  5625751.133   NaN   NaN  2873.870  19502.294  28024.0   NaN   
2    1995-03-01  6555991.556   NaN   NaN  3650.007  22124.574  32894.0   NaN   
3    1995-04-01  5628182.383   NaN   NaN  4573.721  19504.515  38988.0   NaN   
4    1995-05-01  5783096.492   NaN   NaN  5117.085  20737.614  44153.0   NaN   
..          ...          ...   ...   ...       ...        ...      ...   ...   
379  2026-08-01          NaN   NaN   NaN       NaN        NaN      NaN   NaN   
380  2026-09-01          NaN   NaN   NaN       NaN        NaN      NaN   NaN   
381  2026-10-01          NaN   NaN   NaN       NaN        NaN      NaN   NaN   
382  2026-11-01          NaN   NaN   NaN       NaN        NaN      NaN   NaN   
383  2026-12-01          NaN   NaN   NaN       NaN        NaN      NaN   NaN   

     exp8  exp9     exp10         exp11  exp12  
0     NaN   NaN  43.49076  8.581366e+06    NaN  
1     NaN   NaN  43.88784  9.535998e+06    NaN  
2     NaN   NaN  43.69789  1.067358e+07    NaN  
3     NaN   NaN  45.15942  9.031623e+06    NaN  
4     NaN   NaN  43.50870  9.424005e+06    NaN  
..    ...   ...       ...           ...    ...  
379   NaN   NaN       NaN           NaN    NaN  
380   NaN   NaN       NaN           NaN    NaN  
381   NaN   NaN       NaN           NaN    NaN  
382   NaN   NaN       NaN           NaN    NaN  
383   NaN   NaN       NaN           NaN    NaN  

[384 rows x 13 columns]

In [9]:
or_values = original_values.to_numpy()

or_values = or_values[:, 1:6]
or_values

array([[5065287.362, nan, nan, 2962.878, 18261.007],
       [5625751.133, nan, nan, 2873.87, 19502.294],
       [6555991.556, nan, nan, 3650.007, 22124.574],
       ...,
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan]], shape=(384, 5), dtype=object)

In [10]:
print(np.shape(fact_load.T))
print(np.shape(or_values))

y = np.dot(fact_load.T, or_values)
# print(y.shape)

# y

(5, 36)
(384, 5)
